#.yaml
#
#Never use GUI opts, only cli overrides
#unless a SE must be involved
#
#lab_x.y.z, 

AWSTemplateFormatVersion: 2010-09-09
Description: >
  TODO

#PARAMETERS#################################################

Parameters:

  SomeThing:
    Description: XYZ 
    Type: String
    AllowedPattern: ^[0-9a-zA-Z]+$
    Default: ABC

#RESOURCES##################################################

Resources:

  SimpleBucket:
      Type: AWS::S3::Bucket
