#param_bucket.yaml
#
#Never use GUI opts, only cli overrides
#unless a SE must be involved
#
#lab_1.1.2, Create a bucket using a parameter for the name 

AWSTemplateFormatVersion: 2010-09-09
Description: >
  Parameter named bucket

#PARAMETERS#################################################

Parameters:

  UserName:
    Description: >
      User Name
    NoEcho: True
    Type: String
    Default: "NewLabUser"

  Password:
    Description: >
      User password
    NoEcho: True
    Type: String

#RESOURCES##################################################

Transform: 'AWS::Serverless-2016-10-31'
Resources:

  LabUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref Password
      UserName: !Ref UserName
      ManagedPolicyArns:
        - !ImportValue "CFStellULabsPolicy"
